name: Image
on:
  workflow_call:
    inputs:
      push:
        required: true
        default: false
        type: boolean
        description: "If image should be pushed"
      cache_tag:
        required: false
        default: main
        type: string
        description: "Branch or tag to use for caching"
      user:
        required: true
        type: string
        description: "GHCR User"            

jobs:
  docker:
    env:
      IMAGE_NAME: ghcr.io/${{ inputs.user }}/cadency_rs
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write            
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract docker meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=tag
            type=ref,event=branch
            type=sha
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ inputs.cache_tag }}
          cache-to: type=inline
      - name: Image pushed
        if: inputs.push
        run: echo "Image pushed"
